### ISSUE TITLE
V2 Rewrite

### ISSUE THREAD

**Issue by Hoi15A** [Hoi15A/TBDUtils#21]
# TODO:

**Plugin Build**
- [x] Update dependencies
- [x] Better test environment
- [ ] Certain dependencies should be optional (simplevoice, discordsrv)
- [ ] GitHub actions

**Commands**
- [x] Command structure (basecommand, builder, that kind of stuff)
- [x] Confirmation
- [ ] Port existing commands

**Events**
- [x] Event structure
- [ ] Port required events

**New Chat**
- [x] Minimessage in chat would be fun
- [x] Quick reply with /r
- [x] Clean format
- [x] Noxesium support (even if not at launch)

**Optional Dependencies**
- [ ] SimpleVoice plugin that only enables when present
- [ ] Better unified tab icon system (for voice info)
- [ ] Single DiscordSRV interface/function for forwarding plugin messages to discord
- [ ] Hypixel API update if we wanna keep /boop

**Other/Optional**
- [ ] Translation keys for plugin messages
- [ ] No more pushing straight to master/feature branches might be smart in combination with better GH actions

**Comment by ByrtZ** [comment]
Updated to reflect chat additions and confirmation command addition.
